name: Testing
run-name: ${{ github.actor }} is testing the implementation

on:
  pull_request:
    branches: [main]

jobs:
  setupDev:
    name: ğŸ›  Install Dependencies, ğŸ•µï¸â€â™‚ï¸ Lint and ğŸ§ª Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ğŸ•µï¸â€â™‚ï¸  Lint
         run: invoke lint

      - name: ğŸ§ª  Test
         run: invoke test
